/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop_Principal = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        img_fundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menCadUser = new javax.swing.JMenuItem();
        MenCadCli = new javax.swing.JMenuItem();
        MenCadEntrada = new javax.swing.JMenuItem();
        MenCadSaida = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        MenRelEntrada = new javax.swing.JMenuItem();
        MenRelSaida = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        MenAjuSobre = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        MenOpcSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("TelaPrincipal"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout Desktop_PrincipalLayout = new javax.swing.GroupLayout(Desktop_Principal);
        Desktop_Principal.setLayout(Desktop_PrincipalLayout);
        Desktop_PrincipalLayout.setHorizontalGroup(
            Desktop_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );
        Desktop_PrincipalLayout.setVerticalGroup(
            Desktop_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        getContentPane().add(Desktop_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1270, 570));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Icon/user.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Source Code Pro", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bem Vindo(a)");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 170, 30));

        lbl_data.setFont(new java.awt.Font("Source Code Pro", 1, 14)); // NOI18N
        lbl_data.setForeground(new java.awt.Color(255, 255, 255));
        lbl_data.setText("19/06/2020");
        lbl_data.setToolTipText("Data hoje");
        getContentPane().add(lbl_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 170, 30));

        lbl_user.setFont(new java.awt.Font("Source Code Pro", 1, 14)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(255, 255, 255));
        lbl_user.setText("Carlos Daniel");
        lbl_user.setToolTipText("");
        getContentPane().add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 170, 30));

        img_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/TOCK.jpg"))); // NOI18N
        getContentPane().add(img_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 221));

        menuCadastro.setText("Cadastro");

        menCadUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menCadUser.setText("Usuário");
        menCadUser.setEnabled(false);
        menCadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUserActionPerformed(evt);
            }
        });
        menuCadastro.add(menCadUser);

        MenCadCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenCadCli.setText("Cliente");
        menuCadastro.add(MenCadCli);

        MenCadEntrada.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenCadEntrada.setText("Entrada");
        menuCadastro.add(MenCadEntrada);

        MenCadSaida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenCadSaida.setText("Saída");
        menuCadastro.add(MenCadSaida);

        jMenuBar1.add(menuCadastro);

        menuRelatorio.setText("Relatório");
        menuRelatorio.setEnabled(false);

        MenRelEntrada.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenRelEntrada.setText("Entrada");
        MenRelEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenRelEntradaActionPerformed(evt);
            }
        });
        menuRelatorio.add(MenRelEntrada);

        MenRelSaida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenRelSaida.setText("Saída");
        menuRelatorio.add(MenRelSaida);

        jMenuBar1.add(menuRelatorio);

        menuAjuda.setText("Ajuda");

        MenAjuSobre.setText("Sobre");
        MenAjuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAjuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(MenAjuSobre);

        jMenuBar1.add(menuAjuda);

        menuOpcoes.setText("Opções");

        MenOpcSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenOpcSair.setText("Sair");
        MenOpcSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOpcSairActionPerformed(evt);
            }
        });
        menuOpcoes.add(MenOpcSair);

        jMenuBar1.add(menuOpcoes);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1280, 776));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenRelEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenRelEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenRelEntradaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TUDO ABAIXO ACONTECE AO INICIAR O FORM
        // Inserindo a data na lbldata
        Date date = new Date();
        DateFormat formatDate = DateFormat.getDateInstance(DateFormat.SHORT); // formata a data (SHORT) mostrar somente a data
        lbl_data.setText(formatDate.format(date));
    }//GEN-LAST:event_formWindowActivated

    // BOTÃO SAIR
    private void MenOpcSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOpcSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair? ","Atenção", JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_MenOpcSairActionPerformed

    // BOTÃO SOBRE
    private void MenAjuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAjuSobreActionPerformed
        // TODO add your handling code here:
        Sobre TelaSobre = new Sobre();
        TelaSobre.setVisible(true);
    }//GEN-LAST:event_MenAjuSobreActionPerformed

    // BOTÃO CADASTRAR USUÁRIO
    private void menCadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUserActionPerformed
        // abre form usuário na tela principal
        UserView userView = new UserView();
        //UserView.txtIdCli.setVisible(false); // Oculta o txtid cli
        userView.setVisible(true); // torna visível o form user
        Desktop_Principal.add(userView); // adiciona o form dentro da tela principal
    }//GEN-LAST:event_menCadUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop_Principal;
    private javax.swing.JMenuItem MenAjuSobre;
    private javax.swing.JMenuItem MenCadCli;
    private javax.swing.JMenuItem MenCadEntrada;
    private javax.swing.JMenuItem MenCadSaida;
    private javax.swing.JMenuItem MenOpcSair;
    private javax.swing.JMenuItem MenRelEntrada;
    private javax.swing.JMenuItem MenRelSaida;
    private javax.swing.JLabel img_fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_data;
    public static javax.swing.JLabel lbl_user;
    public static javax.swing.JMenuItem menCadUser;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuOpcoes;
    public static javax.swing.JMenu menuRelatorio;
    // End of variables declaration//GEN-END:variables
}
